# Uses the inherited slim al-folio Docker image until an unaltraweb image exists.
services:
  jekyll:
    image: amirpourmand/al-folio:slim
    #build: .
    ports:
      - 4002:8080
      - 35730:35729
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
